### ISSUE TITLE
why use console and alert not working in class component

### ISSUE THREAD

**Issue by bobwatcherx** [nanojsx/nano-jsx-deno-example#4]
**Describe the bug**
i use deno version 1.24.3
I use class component and try to do console.log on button click but it doesn't work and alert doesn't work either

**Have a question?**
besides that I also want to change the state with setState and the result does not change the state
and lifecycles like didMount willMount all don't work
my code:
```
import { h,Component,Store } from "../dep.ts"

export class Hello extends Component {

  constructor(){
    super();
    this.state ={
      names:[],
      nama:"jono"
    }
  }
    async didMount() {
  
    alert("!23213")
  }
  tampil(){
    this.setState({nama:"12312312"})
  }
  render() {
    return (
      <div>
      <button onClick={()=>this.tampil()}>add</button>
    </div>
    )
  }
}
```

**Comment by yandeu** [comment]
This template does only server side render things. To make it work in the browser, you have to hydrate the Hello component.

I will try to update this template.

**Comment by yandeu** [comment]
I just added an island architecture to this template. Please have a look.
